name = "AFL"
uuid = "c50de976-bb92-4c9e-b7a6-b1cf018338e7"
authors = ["Joost <sevenfourtwo@protonmail.com> and contributors"]
version = "0.1.0"

[deps]
AFLplusplus_jll = "2a46d845-6c66-546d-9393-effbe7e72607"
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"

[compat]
julia = "1.5"
