name = "AFL"
uuid = "c50de976-bb92-4c9e-b7a6-b1cf018338e7"
authors = ["Joost <sevenfourtwo@protonmail.com> and contributors"]
version = "0.1.0"

[deps]
AFL_jll = "97a75533-01f8-5f0b-a19e-1dd09d2fab95"

[compat]
julia = "1.5"
